before_script:
  - apt-get update -qy
  - apt-get install -y g++ gcc libapt-pkg-dev
  - pip install tox setuptools pbr
  - pip install git+git://anonscm.debian.org/apt/python-apt.git@1.1.0_beta1

py27:
  stage: test
  image: python:2.6
  script:
    - tox -e py26

py27:
  stage: test
  image: python:2.7
  script:
    - tox -e py27

py34:
  stage: test
  image: python:3.4
  script:
    - tox -e py34

py35:
  stage: test
  image: python:3.5
  script:
    - tox -e py35
pep8:
  image: python:latest
  stage: test
  script:
    - tox -e pep8
